### ISSUE TITLE
Algorithms

### ISSUE THREAD

**Issue by denregr** [leandrotk/algorithms#8]

**Comment by leandrotk** [comment]
@denregr, can you add a description to this issue, please? Let me know if I can help you in any way.

**Comment by denregr** [comment]
> @denregr, can you add a description to this issue, please? Let me know if I can help you in any way.


Sorry, I just started to study computer science and have not figured out the github yet (I thought this button would bookmark me)

**Comment by leandrotk** [comment]
No worries, @denregr! You can bookmark by clicking on the `Star` button.
